spring:
  datasource:
    # url: jdbc:h2:mem:payments
    url: jdbc:h2:file:./data/payments;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
card-number-length: 18
